#!/usr/bin/env tsx
import { PrismaClient } from '@prisma/client'
import type {
  BatsonNormalizedRecord,
  NormalizedBlank,
  NormalizedGuide,
  NormalizedTipTop,
  NormalizedGrip,
  NormalizedReelSeat,
  NormalizedTrim,
  NormalizedEndCap,
} from '../../app/domain/catalog/batsonNormalizedTypes'

const prisma = new PrismaClient()

const blanks: NormalizedBlank[] = [
  {
    productCode: 'IMMWS84MH',
    brand: 'RainShadow',
    series: 'IMMWS',
    family: 'castingBlank',
    material: 'RX7 Graphite',
    msrp: 189.99,
    availability: 'inStock',
    color: 'Carbon',
    itemTotalLengthIn: 84,
    numberOfPieces: 1,
    power: 'MH',
    action: 'F',
    application: ['bass'],
    blankType: 'casting',
    materialConstruction: 'RX7 Graphite',
    lineRating: '10-17 lb',
    lureRating: '1/4-1 oz',
    tipOD_mm: 4.5,
    buttOD_mm: 13.5,
    blankWeightOz: 1.9,
    intrinsicPower_g: 520,
    actionAngle_deg: 78,
    ern: 12,
    tenInDiameter_mm: 9.5,
    twentyInDiameter_mm: 11.2,
    thirtyInDiameter_mm: 12.4,
    finish: 'Gloss',
    notes: 'Pilot blank',
    suitableFor: ['bass'],
  },
  {
    productCode: 'IMMWS72ML',
    brand: 'RainShadow',
    series: 'IMMWS',
    family: 'spinningBlank',
    material: 'RX7 Graphite',
    msrp: 179.99,
    availability: 'inStock',
    color: 'Carbon',
    itemTotalLengthIn: 72,
    numberOfPieces: 2,
    power: 'ML',
    action: 'F',
    application: ['walleye'],
    blankType: 'spinning',
    materialConstruction: 'RX7 Graphite',
    lineRating: '6-12 lb',
    lureRating: '1/8-1/2 oz',
    tipOD_mm: 4.0,
    buttOD_mm: 12.0,
    blankWeightOz: 1.6,
    intrinsicPower_g: 400,
    actionAngle_deg: 76,
    ern: 10,
    tenInDiameter_mm: 9.0,
    twentyInDiameter_mm: 10.8,
    thirtyInDiameter_mm: 12.0,
    finish: 'Matte',
    notes: 'Pilot blank 2',
    suitableFor: ['walleye'],
  },
]

const guides: NormalizedGuide[] = [
  {
    productCode: 'MXN5',
    brand: 'ALPS',
    series: 'MXN',
    family: 'singleFootGuide',
    material: 'Stainless Steel',
    msrp: 4.99,
    availability: 'inStock',
    color: 'Black',
    frameMaterial: 'Stainless Steel',
    frameMaterialCode: 'SS316',
    frameFinish: 'Powder Black',
    ringMaterial: 'SIC',
    ringMaterialCode: 'SIC',
    ringSize: 5,
    tubeSize: null,
    footType: 'single',
    height_mm: 15,
    weightOz: 0.05,
    footLength_mm: 12,
    frameProfile: 'low',
    usageHints: 'Spinning set',
    kitContents: undefined,
  },
  {
    productCode: 'HXN10',
    brand: 'ALPS',
    series: 'HXN',
    family: 'doubleFootGuide',
    material: 'Titanium',
    msrp: 9.99,
    availability: 'inStock',
    color: 'Gunmetal',
    frameMaterial: 'Titanium',
    frameMaterialCode: 'Ti',
    frameFinish: 'Gunmetal',
    ringMaterial: 'Zirconia',
    ringMaterialCode: 'Zr',
    ringSize: 10,
    tubeSize: null,
    footType: 'double',
    height_mm: 28,
    weightOz: 0.09,
    footLength_mm: 20,
    frameProfile: 'high',
    usageHints: 'Casting stripper',
    kitContents: undefined,
  },
]

const tipTops: NormalizedTipTop[] = [
  {
    productCode: 'FSTT-4.5-6',
    brand: 'Forecast',
    series: 'FSTT',
    family: 'castingTipTop',
    material: 'SS316',
    msrp: 3.49,
    availability: 'inStock',
    color: 'Polished',
    frameMaterial: 'Stainless Steel',
    frameMaterialCode: 'SS316',
    frameFinish: 'Chrome',
    ringMaterial: 'SIC',
    ringMaterialCode: 'SIC',
    ringSize: 6,
    tubeSize: 4.5,
    tipTopType: 'Heavy Duty',
    displayName: 'Forecast FSTT 6',
    weightOz: 0.03,
    height_mm: 18,
    notes: 'Pilot tip top',
    pricingTier: 'HD',
  },
  {
    productCode: 'FTT-5-5',
    brand: 'Forecast',
    series: 'FTT',
    family: 'spinningTipTop',
    material: 'SS316',
    msrp: 3.19,
    availability: 'inStock',
    color: 'Black',
    frameMaterial: 'Stainless Steel',
    frameMaterialCode: 'SS316',
    frameFinish: 'Black',
    ringMaterial: 'Alconite',
    ringMaterialCode: 'AL',
    ringSize: 5,
    tubeSize: 5,
    tipTopType: 'Standard',
    displayName: 'Forecast FTT 5',
    weightOz: 0.025,
    height_mm: 17,
    notes: 'Pilot tip top 2',
    pricingTier: 'STD',
  },
]

const grips: NormalizedGrip[] = [
  {
    productCode: 'SG-8.5-EVA',
    brand: 'Forecast',
    series: 'EVA',
    family: 'splitGrip',
    material: 'EVA',
    msrp: 12.99,
    availability: 'inStock',
    color: 'Black',
    category: 'grip',
    designStudioRole: 'HANDLE',
    itemLengthIn: 8.5,
    insideDiameterIn: 0.25,
    frontODIn: 0.9,
    rearODIn: 1.0,
    profileShape: 'split',
    gripPosition: 'rear',
    weight_g: 28,
    urethaneFilled: false,
    winnPattern: undefined,
    texture: 'smooth',
    notes: 'Pilot grip',
  },
  {
    productCode: 'FG-3.5-CORK',
    brand: 'Forecast',
    series: 'Cork',
    family: 'foreGrip',
    material: 'Cork',
    msrp: 9.99,
    availability: 'inStock',
    color: 'Natural',
    category: 'grip',
    designStudioRole: 'HANDLE',
    itemLengthIn: 3.5,
    insideDiameterIn: 0.25,
    frontODIn: 1.0,
    rearODIn: 0.8,
    profileShape: 'tapered',
    gripPosition: 'fore',
    weight_g: 18,
    urethaneFilled: undefined,
    winnPattern: undefined,
    texture: 'smooth',
    notes: 'Pilot grip 2',
  },
]

const reelSeats: NormalizedReelSeat[] = [
  {
    productCode: 'ALPS-RMS16',
    brand: 'ALPS',
    series: 'RMS',
    family: 'spinningSeat',
    material: 'Aluminum',
    msrp: 24.99,
    availability: 'inStock',
    color: 'Black',
    seatSize: '16',
    itemLengthIn: 5.5,
    insideDiameterIn: 0.5,
    bodyOutsideDiameterIn: 0.9,
    seatOrientation: 'upLock',
    hoodOutsideDiameterIn: 1.1,
    insertMaterial: 'Graphite',
    threadSpec: 'M16',
    hardwareFinish: 'Anodized',
    weightOz: 1.8,
  },
  {
    productCode: 'ALPS-TRIGGER17',
    brand: 'ALPS',
    series: 'Trigger',
    family: 'triggerCastingSeat',
    material: 'Graphite',
    msrp: 21.99,
    availability: 'inStock',
    color: 'Matte',
    seatSize: '17',
    itemLengthIn: 5.8,
    insideDiameterIn: 0.55,
    bodyOutsideDiameterIn: 1.05,
    seatOrientation: 'trigger',
    hoodOutsideDiameterIn: 1.2,
    insertMaterial: 'Graphite',
    threadSpec: 'M17',
    hardwareFinish: 'Matte',
    weightOz: 1.9,
  },
]

const trims: NormalizedTrim[] = [
  {
    productCode: 'TR-14-BLK',
    brand: 'Forecast',
    series: 'Trim',
    family: 'trimRing',
    material: 'Aluminum',
    msrp: 3.49,
    availability: 'inStock',
    color: 'Black',
    itemLengthIn: 0.5,
    insideDiameterIn: 0.5,
    outsideDiameterIn: 0.8,
    heightIn: 0.2,
    weightOz: 0.01,
    plating: 'Black',
    pattern: 'smooth',
    notes: 'Trim ring',
  },
  {
    productCode: 'TR-16-GM',
    brand: 'Forecast',
    series: 'Trim',
    family: 'trimRing',
    material: 'Aluminum',
    msrp: 3.69,
    availability: 'inStock',
    color: 'Gunmetal',
    itemLengthIn: 0.5,
    insideDiameterIn: 0.55,
    outsideDiameterIn: 0.85,
    heightIn: 0.2,
    weightOz: 0.01,
    plating: 'Gunmetal',
    pattern: 'smooth',
    notes: 'Trim ring 2',
  },
]

const endCaps: NormalizedEndCap[] = [
  {
    productCode: 'BC-25-RB',
    brand: 'Forecast',
    series: 'ButtCap',
    family: 'buttCap',
    material: 'Rubber',
    msrp: 6.99,
    availability: 'inStock',
    color: 'Black',
    itemLengthIn: 1.5,
    insideDiameterIn: 0.75,
    outsideDiameterIn: 1.25,
    endCapDepthIn: 0.75,
    weightOz: 0.6,
    hardwareInterface: 'Press-fit',
    notes: 'Butt cap',
  },
  {
    productCode: 'BC-28-AL',
    brand: 'ALPS',
    series: 'Gimbal',
    family: 'gimbal',
    material: 'Aluminum',
    msrp: 14.99,
    availability: 'inStock',
    color: 'Silver',
    itemLengthIn: 2.0,
    insideDiameterIn: 0.85,
    outsideDiameterIn: 1.5,
    endCapDepthIn: 1.0,
    weightOz: 1.0,
    hardwareInterface: 'Pin',
    notes: 'Gimbal cap',
  },
]

const samples: Array<{
  supplierSlug: string
  partType: string
  title: string
  normalized: BatsonNormalizedRecord
}> = [
  ...blanks.map(n => ({ supplierSlug: 'batson-rod-blanks', partType: 'Rod Blank', title: `${n.brand} ${n.productCode}`, normalized: n })),
  ...guides.map(n => ({ supplierSlug: 'batson-guides-tops', partType: 'Guide', title: `${n.brand} ${n.productCode}`, normalized: n })),
  ...tipTops.map(n => ({ supplierSlug: 'batson-guides-tops', partType: 'Tip Top', title: `${n.brand} ${n.productCode}`, normalized: n })),
  ...grips.map(n => ({ supplierSlug: 'batson-grips', partType: 'Grip', title: `${n.brand} ${n.productCode}`, normalized: n })),
  ...reelSeats.map(n => ({ supplierSlug: 'batson-reel-seats', partType: 'Reel Seat', title: `${n.brand} ${n.productCode}`, normalized: n })),
  ...trims.map(n => ({ supplierSlug: 'batson-trim-pieces', partType: 'Trim', title: `${n.brand} ${n.productCode}`, normalized: n })),
  ...endCaps.map(n => ({ supplierSlug: 'batson-end-caps-gimbals', partType: 'End Cap', title: `${n.brand} ${n.productCode}`, normalized: n })),
]

async function run() {
  await prisma.partStaging.deleteMany()
  let counter = 0
  for (const sample of samples) {
    await prisma.partStaging.create({
      data: {
        supplierId: sample.supplierSlug,
        externalId: sample.normalized.productCode,
        title: sample.title,
        partType: sample.partType,
        description: `${sample.partType} pilot sample`,
        rawSpecs: {},
        normSpecs: sample.normalized,
        priceMsrp: sample.normalized.msrp ?? null,
        availability: sample.normalized.availability ?? null,
        fetchedAt: new Date(),
      },
    })
    counter += 1
  }
  console.log('[seedBatsonPilotData] inserted rows:', counter)
}

run()
  .catch(err => {
    console.error('[seedBatsonPilotData] failed:', err)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
